### ISSUE TITLE
environment VERSION

### ISSUE THREAD

**Issue by empereira** [fametec/glpi#15]
Buenas,

A variavel VERSION: "9.5.1" configurada no .yml vai substituir a variavel do install_glpi.sh?

Caso não, como faço isso via .yml?

**Comment by eduardofraga** [comment]
Veja a versao 9.5.1 em https://github.com/fametec/glpi/tree/9.5.1/docker

**Comment by empereira** [comment]
vlw...

**Comment by empereira** [comment]
To usando teu dockerfile em modo stack com traefik.

Tentei setar uma env pro mariadb, mas parece que não sobrescreve.

```
version: "3.5"
services:
  mariadb-glpi:
    image: fametec/glpi:mariadb
    hostname: mariadb
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb-glpi-volume:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi-user
      MYSQL_PASSWORD: glpi-pass
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_RANDOM_ROOT_PASSWORD: 0
```
Como posso fazer isso?
